/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutAnunciosRouteImport } from './routes/_layout.anuncios'
import { Route as LayoutCategoriasRouteImport } from './routes/_layout.categorias'
import { Route as LayoutComisionesRouteImport } from './routes/_layout.comisiones'
import { Route as LayoutConfiguracionRouteImport } from './routes/_layout.configuracion'
import { Route as LayoutConsejosRouteImport } from './routes/_layout.consejos'
import { Route as LayoutContactosRouteImport } from './routes/_layout.contactos'
import { Route as LayoutCuponesRouteImport } from './routes/_layout.cupones'
import { Route as LayoutHomeRouteImport } from './routes/_layout.home'
import { Route as LayoutNegociosRouteImport } from './routes/_layout.negocios'
import { Route as LayoutOfertasRouteImport } from './routes/_layout.ofertas'
import { Route as LayoutOrdenesRouteImport } from './routes/_layout.ordenes'
import { Route as LayoutPagosRouteImport } from './routes/_layout.pagos'
import { Route as LayoutReportesRouteImport } from './routes/_layout.reportes'
import { Route as LayoutResenasRouteImport } from './routes/_layout.resenas'
import { Route as LayoutSlidesRouteImport } from './routes/_layout.slides'
import { Route as LayoutCampanasMailsRouteImport } from './routes/_layout.campanas.mails'
import { Route as LayoutCampanasPushRouteImport } from './routes/_layout.campanas.push'
import { Route as LayoutCampanasSegmentosRouteImport } from './routes/_layout.campanas.segmentos'
import { Route as LayoutNotificacionesMailsRouteImport } from './routes/_layout.notificaciones.mails'
import { Route as LayoutNotificacionesPushRouteImport } from './routes/_layout.notificaciones.push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAnunciosRoute = LayoutAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriasRoute = LayoutCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComisionesRoute = LayoutComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfiguracionRoute = LayoutConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsejosRoute = LayoutConsejosRouteImport.update({
  id: '/consejos',
  path: '/consejos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactosRoute = LayoutContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCuponesRoute = LayoutCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNegociosRoute = LayoutNegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOfertasRoute = LayoutOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdenesRoute = LayoutOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPagosRoute = LayoutPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportesRoute = LayoutReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResenasRoute = LayoutResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlidesRoute = LayoutSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCampanasMailsRoute = LayoutCampanasMailsRouteImport.update({
  id: '/campanas/mails',
  path: '/campanas/mails',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCampanasPushRoute = LayoutCampanasPushRouteImport.update({
  id: '/campanas/push',
  path: '/campanas/push',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCampanasSegmentosRoute = LayoutCampanasSegmentosRouteImport.update({
  id: '/campanas/segmentos',
  path: '/campanas/segmentos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificacionesMailsRoute =
  LayoutNotificacionesMailsRouteImport.update({
    id: '/notificaciones/mails',
    path: '/notificaciones/mails',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutNotificacionesPushRoute =
  LayoutNotificacionesPushRouteImport.update({
    id: '/notificaciones/push',
    path: '/notificaciones/push',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anuncios': typeof LayoutAnunciosRoute
  '/categorias': typeof LayoutCategoriasRoute
  '/comisiones': typeof LayoutComisionesRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/consejos': typeof LayoutConsejosRoute
  '/contactos': typeof LayoutContactosRoute
  '/cupones': typeof LayoutCuponesRoute
  '/home': typeof LayoutHomeRoute
  '/negocios': typeof LayoutNegociosRoute
  '/ofertas': typeof LayoutOfertasRoute
  '/ordenes': typeof LayoutOrdenesRoute
  '/pagos': typeof LayoutPagosRoute
  '/reportes': typeof LayoutReportesRoute
  '/resenas': typeof LayoutResenasRoute
  '/slides': typeof LayoutSlidesRoute
  '/campanas/mails': typeof LayoutCampanasMailsRoute
  '/campanas/push': typeof LayoutCampanasPushRoute
  '/campanas/segmentos': typeof LayoutCampanasSegmentosRoute
  '/notificaciones/mails': typeof LayoutNotificacionesMailsRoute
  '/notificaciones/push': typeof LayoutNotificacionesPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/anuncios': typeof LayoutAnunciosRoute
  '/categorias': typeof LayoutCategoriasRoute
  '/comisiones': typeof LayoutComisionesRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/consejos': typeof LayoutConsejosRoute
  '/contactos': typeof LayoutContactosRoute
  '/cupones': typeof LayoutCuponesRoute
  '/home': typeof LayoutHomeRoute
  '/negocios': typeof LayoutNegociosRoute
  '/ofertas': typeof LayoutOfertasRoute
  '/ordenes': typeof LayoutOrdenesRoute
  '/pagos': typeof LayoutPagosRoute
  '/reportes': typeof LayoutReportesRoute
  '/resenas': typeof LayoutResenasRoute
  '/slides': typeof LayoutSlidesRoute
  '/campanas/mails': typeof LayoutCampanasMailsRoute
  '/campanas/push': typeof LayoutCampanasPushRoute
  '/campanas/segmentos': typeof LayoutCampanasSegmentosRoute
  '/notificaciones/mails': typeof LayoutNotificacionesMailsRoute
  '/notificaciones/push': typeof LayoutNotificacionesPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/anuncios': typeof LayoutAnunciosRoute
  '/_layout/categorias': typeof LayoutCategoriasRoute
  '/_layout/comisiones': typeof LayoutComisionesRoute
  '/_layout/configuracion': typeof LayoutConfiguracionRoute
  '/_layout/consejos': typeof LayoutConsejosRoute
  '/_layout/contactos': typeof LayoutContactosRoute
  '/_layout/cupones': typeof LayoutCuponesRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/negocios': typeof LayoutNegociosRoute
  '/_layout/ofertas': typeof LayoutOfertasRoute
  '/_layout/ordenes': typeof LayoutOrdenesRoute
  '/_layout/pagos': typeof LayoutPagosRoute
  '/_layout/reportes': typeof LayoutReportesRoute
  '/_layout/resenas': typeof LayoutResenasRoute
  '/_layout/slides': typeof LayoutSlidesRoute
  '/_layout/campanas/mails': typeof LayoutCampanasMailsRoute
  '/_layout/campanas/push': typeof LayoutCampanasPushRoute
  '/_layout/campanas/segmentos': typeof LayoutCampanasSegmentosRoute
  '/_layout/notificaciones/mails': typeof LayoutNotificacionesMailsRoute
  '/_layout/notificaciones/push': typeof LayoutNotificacionesPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anuncios'
    | '/categorias'
    | '/comisiones'
    | '/configuracion'
    | '/consejos'
    | '/contactos'
    | '/cupones'
    | '/home'
    | '/negocios'
    | '/ofertas'
    | '/ordenes'
    | '/pagos'
    | '/reportes'
    | '/resenas'
    | '/slides'
    | '/campanas/mails'
    | '/campanas/push'
    | '/campanas/segmentos'
    | '/notificaciones/mails'
    | '/notificaciones/push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/anuncios'
    | '/categorias'
    | '/comisiones'
    | '/configuracion'
    | '/consejos'
    | '/contactos'
    | '/cupones'
    | '/home'
    | '/negocios'
    | '/ofertas'
    | '/ordenes'
    | '/pagos'
    | '/reportes'
    | '/resenas'
    | '/slides'
    | '/campanas/mails'
    | '/campanas/push'
    | '/campanas/segmentos'
    | '/notificaciones/mails'
    | '/notificaciones/push'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/anuncios'
    | '/_layout/categorias'
    | '/_layout/comisiones'
    | '/_layout/configuracion'
    | '/_layout/consejos'
    | '/_layout/contactos'
    | '/_layout/cupones'
    | '/_layout/home'
    | '/_layout/negocios'
    | '/_layout/ofertas'
    | '/_layout/ordenes'
    | '/_layout/pagos'
    | '/_layout/reportes'
    | '/_layout/resenas'
    | '/_layout/slides'
    | '/_layout/campanas/mails'
    | '/_layout/campanas/push'
    | '/_layout/campanas/segmentos'
    | '/_layout/notificaciones/mails'
    | '/_layout/notificaciones/push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/anuncios': {
      id: '/_layout/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof LayoutAnunciosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categorias': {
      id: '/_layout/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof LayoutCategoriasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/comisiones': {
      id: '/_layout/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof LayoutComisionesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configuracion': {
      id: '/_layout/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof LayoutConfiguracionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/consejos': {
      id: '/_layout/consejos'
      path: '/consejos'
      fullPath: '/consejos'
      preLoaderRoute: typeof LayoutConsejosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contactos': {
      id: '/_layout/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof LayoutContactosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cupones': {
      id: '/_layout/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof LayoutCuponesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/negocios': {
      id: '/_layout/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof LayoutNegociosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ofertas': {
      id: '/_layout/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof LayoutOfertasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ordenes': {
      id: '/_layout/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof LayoutOrdenesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pagos': {
      id: '/_layout/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof LayoutPagosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes': {
      id: '/_layout/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof LayoutReportesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resenas': {
      id: '/_layout/resenas'
      path: '/resenas'
      fullPath: '/resenas'
      preLoaderRoute: typeof LayoutResenasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/slides': {
      id: '/_layout/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof LayoutSlidesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/campanas/mails': {
      id: '/_layout/campanas/mails'
      path: '/campanas/mails'
      fullPath: '/campanas/mails'
      preLoaderRoute: typeof LayoutCampanasMailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/campanas/push': {
      id: '/_layout/campanas/push'
      path: '/campanas/push'
      fullPath: '/campanas/push'
      preLoaderRoute: typeof LayoutCampanasPushRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/campanas/segmentos': {
      id: '/_layout/campanas/segmentos'
      path: '/campanas/segmentos'
      fullPath: '/campanas/segmentos'
      preLoaderRoute: typeof LayoutCampanasSegmentosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notificaciones/mails': {
      id: '/_layout/notificaciones/mails'
      path: '/notificaciones/mails'
      fullPath: '/notificaciones/mails'
      preLoaderRoute: typeof LayoutNotificacionesMailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notificaciones/push': {
      id: '/_layout/notificaciones/push'
      path: '/notificaciones/push'
      fullPath: '/notificaciones/push'
      preLoaderRoute: typeof LayoutNotificacionesPushRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAnunciosRoute: typeof LayoutAnunciosRoute
  LayoutCategoriasRoute: typeof LayoutCategoriasRoute
  LayoutComisionesRoute: typeof LayoutComisionesRoute
  LayoutConfiguracionRoute: typeof LayoutConfiguracionRoute
  LayoutConsejosRoute: typeof LayoutConsejosRoute
  LayoutContactosRoute: typeof LayoutContactosRoute
  LayoutCuponesRoute: typeof LayoutCuponesRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutNegociosRoute: typeof LayoutNegociosRoute
  LayoutOfertasRoute: typeof LayoutOfertasRoute
  LayoutOrdenesRoute: typeof LayoutOrdenesRoute
  LayoutPagosRoute: typeof LayoutPagosRoute
  LayoutReportesRoute: typeof LayoutReportesRoute
  LayoutResenasRoute: typeof LayoutResenasRoute
  LayoutSlidesRoute: typeof LayoutSlidesRoute
  LayoutCampanasMailsRoute: typeof LayoutCampanasMailsRoute
  LayoutCampanasPushRoute: typeof LayoutCampanasPushRoute
  LayoutCampanasSegmentosRoute: typeof LayoutCampanasSegmentosRoute
  LayoutNotificacionesMailsRoute: typeof LayoutNotificacionesMailsRoute
  LayoutNotificacionesPushRoute: typeof LayoutNotificacionesPushRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnunciosRoute: LayoutAnunciosRoute,
  LayoutCategoriasRoute: LayoutCategoriasRoute,
  LayoutComisionesRoute: LayoutComisionesRoute,
  LayoutConfiguracionRoute: LayoutConfiguracionRoute,
  LayoutConsejosRoute: LayoutConsejosRoute,
  LayoutContactosRoute: LayoutContactosRoute,
  LayoutCuponesRoute: LayoutCuponesRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutNegociosRoute: LayoutNegociosRoute,
  LayoutOfertasRoute: LayoutOfertasRoute,
  LayoutOrdenesRoute: LayoutOrdenesRoute,
  LayoutPagosRoute: LayoutPagosRoute,
  LayoutReportesRoute: LayoutReportesRoute,
  LayoutResenasRoute: LayoutResenasRoute,
  LayoutSlidesRoute: LayoutSlidesRoute,
  LayoutCampanasMailsRoute: LayoutCampanasMailsRoute,
  LayoutCampanasPushRoute: LayoutCampanasPushRoute,
  LayoutCampanasSegmentosRoute: LayoutCampanasSegmentosRoute,
  LayoutNotificacionesMailsRoute: LayoutNotificacionesMailsRoute,
  LayoutNotificacionesPushRoute: LayoutNotificacionesPushRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
