/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutCategoriasRouteImport } from './routes/_layout.categorias'
import { Route as LayoutComisionesRouteImport } from './routes/_layout.comisiones'
import { Route as LayoutConfiguracionRouteImport } from './routes/_layout.configuracion'
import { Route as LayoutConsejosRouteImport } from './routes/_layout.consejos'
import { Route as LayoutEmailsRouteImport } from './routes/_layout.emails'
import { Route as LayoutHomeRouteImport } from './routes/_layout.home'
import { Route as LayoutPagosRouteImport } from './routes/_layout.pagos'
import { Route as LayoutSlidesRouteImport } from './routes/_layout.slides'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCategoriasRoute = LayoutCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutComisionesRoute = LayoutComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfiguracionRoute = LayoutConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsejosRoute = LayoutConsejosRouteImport.update({
  id: '/consejos',
  path: '/consejos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailsRoute = LayoutEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPagosRoute = LayoutPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSlidesRoute = LayoutSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/categorias': typeof LayoutCategoriasRoute
  '/comisiones': typeof LayoutComisionesRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/consejos': typeof LayoutConsejosRoute
  '/emails': typeof LayoutEmailsRoute
  '/home': typeof LayoutHomeRoute
  '/pagos': typeof LayoutPagosRoute
  '/slides': typeof LayoutSlidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/categorias': typeof LayoutCategoriasRoute
  '/comisiones': typeof LayoutComisionesRoute
  '/configuracion': typeof LayoutConfiguracionRoute
  '/consejos': typeof LayoutConsejosRoute
  '/emails': typeof LayoutEmailsRoute
  '/home': typeof LayoutHomeRoute
  '/pagos': typeof LayoutPagosRoute
  '/slides': typeof LayoutSlidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/categorias': typeof LayoutCategoriasRoute
  '/_layout/comisiones': typeof LayoutComisionesRoute
  '/_layout/configuracion': typeof LayoutConfiguracionRoute
  '/_layout/consejos': typeof LayoutConsejosRoute
  '/_layout/emails': typeof LayoutEmailsRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/pagos': typeof LayoutPagosRoute
  '/_layout/slides': typeof LayoutSlidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/categorias'
    | '/comisiones'
    | '/configuracion'
    | '/consejos'
    | '/emails'
    | '/home'
    | '/pagos'
    | '/slides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/categorias'
    | '/comisiones'
    | '/configuracion'
    | '/consejos'
    | '/emails'
    | '/home'
    | '/pagos'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/categorias'
    | '/_layout/comisiones'
    | '/_layout/configuracion'
    | '/_layout/consejos'
    | '/_layout/emails'
    | '/_layout/home'
    | '/_layout/pagos'
    | '/_layout/slides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/categorias': {
      id: '/_layout/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof LayoutCategoriasRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/comisiones': {
      id: '/_layout/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof LayoutComisionesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/configuracion': {
      id: '/_layout/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof LayoutConfiguracionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/consejos': {
      id: '/_layout/consejos'
      path: '/consejos'
      fullPath: '/consejos'
      preLoaderRoute: typeof LayoutConsejosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/emails': {
      id: '/_layout/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof LayoutEmailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/pagos': {
      id: '/_layout/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof LayoutPagosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/slides': {
      id: '/_layout/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof LayoutSlidesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCategoriasRoute: typeof LayoutCategoriasRoute
  LayoutComisionesRoute: typeof LayoutComisionesRoute
  LayoutConfiguracionRoute: typeof LayoutConfiguracionRoute
  LayoutConsejosRoute: typeof LayoutConsejosRoute
  LayoutEmailsRoute: typeof LayoutEmailsRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutPagosRoute: typeof LayoutPagosRoute
  LayoutSlidesRoute: typeof LayoutSlidesRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCategoriasRoute: LayoutCategoriasRoute,
  LayoutComisionesRoute: LayoutComisionesRoute,
  LayoutConfiguracionRoute: LayoutConfiguracionRoute,
  LayoutConsejosRoute: LayoutConsejosRoute,
  LayoutEmailsRoute: LayoutEmailsRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutPagosRoute: LayoutPagosRoute,
  LayoutSlidesRoute: LayoutSlidesRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
