/**
 * Transactional confirmation email for public business onboarding (landing).
 *
 * `auth.admin.createUser()` is the service-role API and never sends mail (unlike
 * `auth.signUp()`, which the mobile consumer path uses), so the API owns this
 * template and delivers it itself through Resend.
 *
 * Email-client constraints (no build step, no CSS-in-JS):
 * - table layout, every visual style inline (clients strip <style> rules);
 * - `role="presentation"` tables plus `bgcolor` so Outlook keeps the surfaces;
 * - a single `@media` block, and only for padding/font nudges, never for layout;
 * - `max-width: 600px` container that stays fluid below it (legible at 320px);
 * - hidden preheader div so the inbox snippet is not the first visible line;
 * - a plain-text alternative is returned next to the HTML part.
 */

/**
 * Brand palette, mirrored from the design system so the email looks like the
 * product: `apps/landing/src/styles.css` (`@theme` Rolé tokens) and
 * `apps/mobile/src/core/theme/colors.ts` (light scheme). Every value below is
 * the same hex as its token there.
 */
const BRAND = {
  /** --color-role-primary / colors.ts `primary` (deep aubergine) */
  primary: '#371949',
  /** --color-role-primary-foreground / colors.ts `primaryForeground` */
  onPrimary: '#FFFFFF',
  /** --color-role-secondary (soft lilac) */
  lilac: '#DCCBF5',
  /** --color-role-background (cream page background) */
  cream: '#FAF9F7',
  /** --color-role-surface-muted / colors.ts `card` */
  lilacSurface: '#F7F3FB',
  /** --color-role-foreground (near-black body text) */
  ink: '#1A1A18',
  /** --color-ink-soft. The brand muted grey (#737373) is only 4.3:1 on cream,
   *  so small print uses this darker neutral instead (7.2:1, WCAG AA). */
  inkSoft: '#5D4E75',
  /** --color-role-border */
  border: '#E5E5E5',
  /** colors.ts `successDark`. `ecoGreen` (#16A34A) is 3.3:1 on white, which
   *  fails AA for the size this is rendered at. */
  ecoGreen: '#15803D',
} as const;

/** Longest business name we put in the subject line before truncating. */
const SUBJECT_NAME_LIMIT = 80;

const HTML_ENTITIES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/**
 * Escapes a value before it reaches the HTML part. The owner's name and the
 * business name are user input from the public onboarding form, so they must
 * never land in markup unescaped.
 */
export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => HTML_ENTITIES[char] ?? char);
}

function truncate(value: string, limit: number): string {
  return value.length > limit
    ? `${value.slice(0, limit - 1).trimEnd()}…`
    : value;
}

function buildSubject(businessName: string): string {
  return `Confirma tu cuenta de Rolé para activar el acceso a ${truncate(businessName, SUBJECT_NAME_LIMIT)}`;
}

function buildText(input: {
  ownerName: string;
  businessName: string;
  confirmationUrl: string;
  supportEmail: string;
}): string {
  return [
    `Hola, ${input.ownerName},`,
    '',
    `Registramos ${input.businessName} en Rolé. Para activar tu cuenta y poder`,
    'gestionar el negocio, confirma este correo con el enlace de un solo uso:',
    '',
    input.confirmationUrl,
    '',
    'Tu negocio sigue en revisión. La confirmación activa tu cuenta, pero el',
    'negocio todavía no se publica: el equipo de Rolé lo aprueba y te avisamos por',
    'este mismo correo cuando esté activo.',
    '',
    `¿Alguna duda? Escríbenos a ${input.supportEmail}.`,
    '',
    '— Equipo de Rolé',
    `Recibiste este mensaje porque registraste un negocio en Rolé con el correo indicado.`,
  ].join('\n');
}

function buildHtml(input: {
  ownerName: string;
  businessName: string;
  confirmationUrl: string;
  supportEmail: string;
}): string {
  // Escaped once, then interpolated: the URL is machine-generated by Supabase,
  // the two names are user input, and the support inbox is configuration.
  const ownerName = escapeHtml(input.ownerName);
  const businessName = escapeHtml(input.businessName);
  const urlText = escapeHtml(input.confirmationUrl);
  // Same escape, safe inside a double-quoted href (quotes are encoded).
  const urlHref = escapeHtml(input.confirmationUrl);
  const supportEmail = escapeHtml(input.supportEmail);

  return `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>Confirma tu cuenta de Rolé</title>
<style>
@media only screen and (max-width: 480px) {
  .card { padding: 24px 20px !important; }
  .cta { font-size: 16px !important; padding: 14px 20px !important; }
}
</style>
</head>
<body style="margin:0;padding:0;background-color:${BRAND.cream};">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;">Confirma tu correo para activar el acceso a ${businessName} en Rolé.</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${BRAND.cream}" style="background-color:${BRAND.cream};">
<tr>
<td align="center" style="padding:24px 12px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;">
<tr>
<td class="card" bgcolor="${BRAND.onPrimary}" style="background-color:${BRAND.onPrimary};border:1px solid ${BRAND.border};border-radius:12px;padding:32px;font-family:Georgia,'Times New Roman',serif;color:${BRAND.ink};">

<p style="margin:0 0 24px;font-family:Georgia,'Times New Roman',serif;font-size:26px;line-height:1.2;font-weight:bold;color:${BRAND.primary};">Rolé</p>

<h1 style="margin:0 0 16px;font-family:Georgia,'Times New Roman',serif;font-size:22px;line-height:1.3;font-weight:bold;color:${BRAND.ink};">Confirma tu cuenta</h1>

<p style="margin:0 0 12px;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.6;color:${BRAND.ink};">Hola, ${ownerName}:</p>

<p style="margin:0 0 24px;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.6;color:${BRAND.ink};">Registramos <strong>${businessName}</strong> en Rolé. Confirma este correo con el botón de abajo para activar tu cuenta y poder gestionar el negocio.</p>

<table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" style="margin:0 0 24px;">
<tr>
<td align="center" bgcolor="${BRAND.primary}" style="background-color:${BRAND.primary};border-radius:8px;">
<a class="cta" href="${urlHref}" style="display:inline-block;padding:14px 28px;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.2;font-weight:bold;color:${BRAND.onPrimary};text-decoration:none;border-radius:8px;">Confirmar mi cuenta en Rolé</a>
</td>
</tr>
</table>

<p style="margin:0 0 8px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6;color:${BRAND.inkSoft};">Si el botón no aparece, copia esta dirección en tu navegador:</p>
<p style="margin:0 0 24px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6;word-break:break-all;word-wrap:break-word;"><a href="${urlHref}" style="color:${BRAND.primary};text-decoration:underline;">${urlText}</a></p>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="${BRAND.lilacSurface}" style="background-color:${BRAND.lilacSurface};border-left:4px solid ${BRAND.lilac};border-radius:6px;">
<tr>
<td style="padding:16px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6;color:${BRAND.ink};">
<strong style="color:${BRAND.ecoGreen};">Tu negocio sigue en revisión.</strong>
La confirmación activa tu cuenta, pero el negocio todavía no se publica. El equipo de Rolé lo aprueba y te avisamos por este mismo correo cuando esté activo.
</td>
</tr>
</table>

<p style="margin:24px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:${BRAND.ink};">¿Alguna duda? Escríbenos a <a href="mailto:${supportEmail}" style="color:${BRAND.primary};">${supportEmail}</a>.</p>

</td>
</tr>
</table>
</td>
</tr>
</table>

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;">
<tr>
<td align="center" style="padding:20px 12px 8px;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.6;color:${BRAND.inkSoft};">
<p style="margin:0 0 6px;">— Equipo de Rolé</p>
<p style="margin:0;">Recibiste este mensaje porque registraste un negocio en Rolé con el correo indicado.</p>
</td>
</tr>
</table>
</body>
</html>`;
}

export interface BusinessConfirmationEmail {
  subject: string;
  html: string;
  text: string;
}

/**
 * Renders the business-owner account confirmation email. The `confirmationUrl`
 * is the `action_link` from `auth.admin.generateLink({ type: 'signup' })`, and
 * `supportEmail` is the business-facing inbox resolved by the caller
 * (`app_config['contact.negocios_email']`) — this function stays pure, so it
 * holds no address of its own.
 */
export function renderBusinessConfirmationEmail(input: {
  ownerName: string;
  businessName: string;
  confirmationUrl: string;
  supportEmail: string;
}): BusinessConfirmationEmail {
  return {
    subject: buildSubject(input.businessName),
    html: buildHtml(input),
    text: buildText(input),
  };
}
