-- Slides promocionales del home móvil (antes hardcodeadas en PromoSlider).
-- type 'ad' = contenido del carrusel promocional gestionable desde admin.
insert into public.slides (title, caption, badge_text, cta_label, redirect_url, image_url, type, priority, active) values
  ('¿Sabías que…',
   'Cada año se desperdician 1.3 mil millones de toneladas de comida en el mundo. ¡Tú puedes ayudar!',
   null,
   'Ver más',
   'https://role.app/about',
   'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&fit=crop',
   'ad', 1, true),
  ('Impacto ambiental',
   'Al rescatar un paquete sorpresa evitas la emisión de ~2.5kg de CO2. Cada rescate cuenta.',
   null,
   'Ver más',
   'https://role.app/how-it-works',
   'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400&fit=crop',
   'ad', 2, true),
  ('Comida rescatada',
   'Los alimentos aptos para consumo pero no para venta son rescatados por negocios como los de Rolé.',
   null,
   'Ver más',
   'https://role.app/about',
   'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&fit=crop',
   'ad', 3, true),
  ('Gana-gana',
   'Rescatar comida no solo ahorra dinero, también reduce el desperdicio y apoya a negocios locales.',
   'Sponsoreado',
   'Ver más',
   'https://role.app/for-business',
   'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&fit=crop',
   'sponsor', 4, true);